### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by amirulskulker** [ryanaidilp/sistem_absensi_pegawai_app#1]
So if someone is new to app development what are the things to change in the code to make it work. Like do we need to creat account somewhere and put api keys and all the. Is there any document to help me get started on the basic configuration?

**Comment by ryanaidilp** [comment]
Hello @amirulskulker, sorry you have to wait long enough. for my answer I've added some information about how to configure the application as well as the backend configuration. I wrote it in Indonesian, but I think you can try to translate it easily. If I have free time, I will try to write it in English.

Hopefully, the information can help you to configure the app, If there are things that confuse you, I am open to helping.
