### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by gop4sch4** [ryanaidilp/sistem_absensi_pegawai_app#28]
Error Login APP
![image](https://user-images.githubusercontent.com/35401990/110073166-82148b80-7db1-11eb-80a0-51b6bf6bbcec.png)

Show On CMD
![image](https://user-images.githubusercontent.com/35401990/110073250-a708fe80-7db1-11eb-8a6c-cf9955ad96d4.png)
How Can i Do , Please, Thank you

![image](https://user-images.githubusercontent.com/35401990/110073750-83928380-7db2-11eb-8294-257bc0c55d62.png)

I'm getting an error on  ( change_pass_screen.dart )
resizeToAvoidBottomPadding and change to  resizeToAvoidBottomInset ,Is it true?

Log laravel ,laravel.log

[2021-03-05 13:34:02] local.ERROR: Trying to access array offset on value of type null {"userId":2,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at C:\\xampp\\htdocs\\sistem_absensi_pegawai\\app\\Exports\\Sheets\\Annual\\HonorerAttendeSheet.php:148)
[stacktrace]
#0 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\app\\Exports\\Sheets\\Annual\\HonorerAttendeSheet.php(148): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', 'C:\\\\xampp\\\\htdocs...', 148, Array)
#1 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\maatwebsite\\excel\\src\\Sheet.php(187): App\\Exports\\Sheets\\Annual\\HonorerAttendeSheet->headings()
#2 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\maatwebsite\\excel\\src\\Sheet.php(210): Maatwebsite\\Excel\\Sheet->open(Object(App\\Exports\\Sheets\\Annual\\HonorerAttendeSheet))
#3 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\maatwebsite\\excel\\src\\Writer.php(67): Maatwebsite\\Excel\\Sheet->export(Object(App\\Exports\\Sheets\\Annual\\HonorerAttendeSheet))
#4 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\maatwebsite\\excel\\src\\Excel.php(195): Maatwebsite\\Excel\\Writer->export(Object(App\\Exports\\AttendeAnnualExport), 'Xlsx')
#5 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\maatwebsite\\excel\\src\\Excel.php(84): Maatwebsite\\Excel\\Excel->export(Object(App\\Exports\\AttendeAnnualExport), 'Daftar Hadir Pe...', 'Xlsx')
#6 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Maatwebsite\\Excel\\Excel->download(Object(App\\Exports\\AttendeAnnualExport), 'Daftar Hadir Pe...')
#7 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\app\\Http\\Controllers\\MainController.php(163): Illuminate\\Support\\Facades\\Facade::__callStatic('download', Array)
#8 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\MainController->download(Object(Illuminate\\Http\\Request))
#9 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('download', Array)
#10 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\MainController), 'download')
#11 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#12 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Routing\\Route->run()
#13 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\inertiajs\\inertia-laravel\\src\\Middleware.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Inertia\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#24 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#32 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#33 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#34 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#35 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 C:\\xampp\\htdocs\\sistem_absensi_pegawai\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"} 

FLUTTER DOCTOR 

S D:\StudioProjects\sistem_absensi_pegawai_app> flutter doctor -v 
[√] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-ID)
    • Flutter version 1.27.0-4.0.pre at D:\tools\flutter
    • Framework revision f8cd24de95 (2 weeks ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\2AKenzArk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
PS D:\StudioProjects\sistem_absensi_pegawai_app>

**Comment by apeh1706** [comment]
@gop4sch4 I'm getting an error on ( change_pass_screen.dart )
resizeToAvoidBottomPadding and change to resizeToAvoidBottomInset ,Is it true?

it will fix the deprecated syntax.

i do have same problem to login into the apps ... 
please kindly give the solution for this problem and thank you very much

**Comment by ryanaidilp** [comment]
The format of the mobile phone numbers in the database must follow this format: 0821 2345 6789
Make sure there are spaces every 4 characters.

**Comment by gop4sch4** [comment]
bang , apa kabar
 saya dengan gunawan

boleh saya minta no tepon bang, pengen ngobroll , ada yg pesan aplikasi
cuman saya mentok
ini no tlpn saya yg ada Whasapp 081395730826

**Comment by gop4sch4** [comment]
Assalamualaikum bang,bang ngomong2 boleh saya minta no tepon bang, pengen
ngobroll , ada yg pesan aplikasi cuman saya mentok
ini no tlpn saya yg ada Whasapp 081395730826
